apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app-test
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: gitops-app
        image: domoda/devopsgcp:v1.0.53
        ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-app
  name: gitops-app-service
  namespace: demo
spec:
  type: NodePort
  ports:
    - name: cgitops-app-port
      port: 80
      nodePort: 30498
      targetPort: 80
  selector:
    app: gitops-app

